services:
  openldap:
    build:
      context: .docker
      dockerfile: ldap/Dockerfile
    container_name: ldapsarapis
    command: '--loglevel debug'
    init: true
    ports:
      - 389:389
      - 636:636
    environment:
      #- 'LANG=fr_FR.UTF-8'
      #- 'LC_ALL=fr_FR.UTF-8'
      - 'LDAP_BACKEND=mdb'
      - 'LDAP_ORGANISATION="GIP RECIA"'
      - 'LDAP_DOMAIN=esco-centre.fr'
      - 'LDAP_BASE_DN=dc=esco-centre,dc=fr'
      #- 'LDAP_LOG_LEVEL=-1'
      - 'LDAP_ADMIN_PASSWORD=admin'
      - 'LDAP_READONLY_USER="false"'
    volumes:
      #- /srv/docker/openldap/container/data:/var/lib/ldap
      - sarapis-ldap-data:/var/lib/ldap
      #- /srv/docker/openldap/container/config:/etc/ldap/slapd.d
      - sarapis-ldap-config:/etc/ldap/slapd.d

volumes:
  sarapis-ldap-data: null
  sarapis-ldap-config: null
